const path = require("path");
const swaggerAutogen = require("swagger-autogen")();

const doc = {
    info: {
        version: "1.0.0",
        title: "Library API",
        description:
            "Documentation automatically generated by the <b>swagger-autogen</b> module.",
    },
    host: "localhost:5000",
    basePath: "/",
    schemes: ["http", "https"],
    consumes: ["application/json"],
    produces: ["application/json"],
};

const outputFile = path.join(__dirname, "swagger", "swagger_output.json");
const endpointsFiles = [
    path.join(__dirname, "routes", "BookRentRoutes.js"),
    path.join(__dirname, "routes", "BookRoutes.js"),
    path.join(__dirname, "routes", "PublisherRoutes.js"),
    path.join(__dirname, "routes", "UserRoutes.js")
];
swaggerAutogen(outputFile, endpointsFiles, doc);
